services:
  app:
    image: ${APP_IMAGE:-}
    platform: linux/amd64
    hostname: lvfe
    build:
      context: ..
      target: ${APP_TARGET}
      dockerfile: ops/Dockerfile
      args:
        APP_GROUP_ID: ${APP_GROUP_ID:-1000}
        APP_USER_ID: ${APP_USER_ID:-1000}
    env_file:
      - ../.env
    ports:
      - ${APP_PORT:-3000}:3000
      - ${DEBUG_PORT:-9000}:9000
    volumes:
      - ../src:/var/www/app

networks:
  default:
    external: true
    name: lv
